### ISSUE TITLE
How to subscribe to the events from the client side so that periodic update will get notified to the client's callback function?

### ISSUE THREAD

**Issue by MrPoudel** [afflux/pysomeip#10]

**Comment by afflux** [comment]
Sorry for the lack of reply. (Also, not sure you deleted your explanatory comment.)

For the sake of other people finding this question: simpleservice is already set up to send out notifications every second (`interval=1`): https://github.com/afflux/pysomeip/blob/b08a17260e934afa4c2f150023be690b25f9add9/tools/simpleservice.py#L21
The reason you are not seeing these is that you used tools/get.py, which is using the SOME/IP RPC, not the PubSub mechanism. You want tools/find-subscribe.py.
