### ISSUE TITLE
Using the get.py example to call the set_time method

### ISSUE THREAD

**Issue by jrhos** [afflux/pysomeip#18]
I am experimenting with the library by using the provided examples in the \tools folder, but I have not figured out a way on how to use service 0xb0a7, method 0x02. What is the proper way to provide a data for this method? If I am not providing any data (i.e. calling the python script as mentioned below), the returned response is MALFORMED_MESSAGE, which is the correct response. Is there any way to provide data for this method in the current implementation? Or do I need to change the implementation of the get.py script?

$ python get.py <ip_address> <port_number> 0xb0a7 0x02 0x01

**Comment by afflux** [comment]
Hi @jrhos, I'm afraid you'll need to adapt get.py if you want to provide non-empty payload on the method call. It's just intended as a trivial example on how to use the API, not a fully featured CLI.
