### ISSUE TITLE
How to use notify_once

### ISSUE THREAD

**Issue by iznogoud-zz** [afflux/pysomeip#3]
Hi,

I am using notify_once to notify all the subscribed clients something has changed.

I register the eventgroup:
`self.register_eventgroup(evg(self))`

and then in the method that receives the message have

```
def method_a(self, someip_message: SOMEIPHeader, addr: _T_SOCKNAME) -> typing.Optional[bytes]:
        self.eventgroups[1].values[0x8010] = someip_message.payload
        self.eventgroups[1].notify_once([0x8010])
```

my problem is that when the notify_once is called the event groups keeps sending the message to the subscribed clients forever.

Am I doing something wrong?

**Comment by afflux** [comment]
Hi,

you should only see continuous notifications if you created a task containing cyclic_notify or if you passed an interval to the SimpleEventgroup constructor: https://github.com/afflux/pysomeip/blob/c1959404db511a7ebe6e33a20761182b072ca6f7/src/someip/service.py#L39-L41

**Comment by iznogoud-zz** [comment]
Thanks for the tip. It's probably that I started form the SimpleService example and in that example the SimpleEventgroup is initialized with 1 second interval, I missed it.

**Comment by iznogoud-zz** [comment]
Thanks it worked.
