### ISSUE TITLE
different package PyPI vs GitHub

### ISSUE THREAD

**Issue by rtazaki** [afflux/pysomeip#4]
## Issue
```
$ py simpleservice.py
Traceback (most recent call last):
  File "c:\work\pysomeip\tools\simpleservice.py", line 14, in <module>
    from someip.service import SimpleEventgroup, SimpleService, MalformedMessageError
ModuleNotFoundError: No module named 'someip.service'
```
## How to steps to issue
`py -m pip install someip`
`py simpleservice.py`

## It works fine
`py -m pip install git+https://github.com/afflux/pysomeip`
`py simpleservice.py`

PyPI and GitHub seem to have different packages for the same version (0.1.2).

### diff
  - config.py
  - header.py
  - sd.py
  - service.py (It does not exist on PyPI)

**Comment by afflux** [comment]
Hi! You're not seeing different packages. You're seeing the git HEAD vs. a released version. You can show the released version on GitHub by clicking on "master" and choosing 0.1.2 under the tags tab.
